# Generated by Django 5.1 on 2024-08-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_staff_image'),
        ('units', '0003_alter_unit_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('ON HOLD', 'On Hold')], default='ACTIVE')),
                ('phase', models.CharField(choices=[('INITIATED', 'Initiated'), ('PLAN & PREPARE', 'Plan & Prepare'), ('BUILD & MANAGE', 'Build & Manage'), ('CLOSE & SUSTAIN', 'Close & Sustain')], default='INITIATED')),
                ('health', models.CharField(choices=[('ORANGE', 'To be started'), ('GREEN', 'On Track'), ('YELLOW', 'Risk Identified'), ('RED', 'Off Track')], default='GREEN')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
    ]
