# Generated by Django 5.1 on 2024-08-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0003_alter_unit_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('EXECUTIVE', [('CEO', 'CEO'), ('CFO', 'CFO')]), ('TECHNICAL', [('SENIOR CONSULTANT', 'Senior Consultant'), ('CONSULTANT', 'Consultant'), ('EXTERNAL CONSULTANT', 'External Consultant')]), ('UNKNOWN', 'Unknown')], default='CONSULTANT', max_length=25)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='staff.staff')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['unit'],
            },
        ),
    ]
