# Generated by Django 5.1 on 2024-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, default='assets/images/staff/avatar1.jpg', upload_to='assets/images/staff/'),
        ),
    ]
