# Generated by Django 5.1 on 2024-08-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('GR', 'Greek'), ('IT', 'Italian'), ('MX', 'Mexican'), ('FF', 'Fastfood'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
