# Generated by Django 5.1 on 2024-08-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
