# Generated by Django 5.1 on 2024-08-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(default='Main Avenue 35, Big City', max_length=200)),
                ('description', models.CharField(default='HR', max_length=256)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
            options={
                'verbose_name_plural': 'Org Unit',
                'ordering': ['name'],
            },
        ),
    ]
